-- CreateTable
CREATE TABLE `blog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(50) NOT NULL,
    `metaTitle` VARCHAR(50) NOT NULL,
    `slug` VARCHAR(50) NOT NULL,
    `summary` VARCHAR(275) NOT NULL,
    `published` BOOLEAN NOT NULL DEFAULT false,
    `content` VARCHAR(2000) NOT NULL,
    `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updateAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
