import NextTopLoaderComponent from "@/components/NextTopLoader";

import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body>
        <NextTopLoaderComponent />
        {children}
      </body>
    </html>
  );
}
