import NextTopLoaderComponent from "@/components/NextTopLoader";
import { Toaster } from "react-hot-toast";

import { Inter } from "next/font/google";
import "./global.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="h-full">
        <NextTopLoaderComponent />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <Toaster />
      </body>
    </html>
  );
}
